#!/bin/bash

# Name of your job
#SBATCH --job-name=aobif_1qoi
#SBATCH --partition=amarsden

# Specify the name of the output file. The %j specifies the job ID
#SBATCH --output=aobif_qoi.o%j

# Specify the name of the error file. The %j specifies the job ID
#SBATCH --error=aobif_qoi.e%j

# The walltime you require for your job
#SBATCH --time=48:00:00

# Job priority. Leave as normal for now
#SBATCH --qos=normal

# Number of nodes are you requesting for your job. You can have 24 processors per node
#SBATCH --nodes=1

# Amount of memory you require per node. The default is 4000 MB per node
#SBATCH --mem=32000

# Number of processors per node
#SBATCH --ntasks-per-node=24

# Send an email to this address when your job starts and finishes
#SBATCH --mail-user=azanoni@stanford.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

# Name of the executable you want to run on the cluster
module purge
module load devel
module load openmpi
module load openblas
module load system
module load x11
module load mesa
module load gcc/12.1.0
module load swig
module load boost
module load armadillo

echo Start time: $(date)

python write_QOI_tables.py

echo End time: $(date)
